IMGFRAME_LANGUAGE_CONTENT = {
    "en": {
        "name": "English",
        "headline": "Give your photos the perfect layout.",
        "blurb": "ImgFrame is a minimalist tool designed to do two things perfectly: add borders to your images and stack multiple photos together. Whether you are preparing a post for social media or creating a quick collage, ImgFrame handles it instantly on your device.",
        "labels": {
            "support": "Support page",
            "home": "Back to Trotyl Home",
        },
    },
    "es": {
        "name": "Español",
        "headline": "Dale el diseño perfecto a tus fotos.",
        "blurb": "ImgFrame es una herramienta minimalista diseñada para hacer dos cosas perfectamente: agregar bordes a tus imágenes y apilar múltiples fotos. Ya sea que estés preparando una publicación para redes sociales o creando un collage rápido, ImgFrame lo maneja al instante en tu dispositivo.",
        "labels": {
            "support": "Página de soporte",
            "home": "Volver a Trotyl Home",
        },
    },
    "fr": {
        "name": "Français",
        "headline": "Donnez à vos photos la mise en page parfaite.",
        "blurb": "ImgFrame est un outil minimaliste conçu pour faire deux choses parfaitement : ajouter des bordures à vos images et empiler plusieurs photos. Que vous prépariez une publication pour les réseaux sociaux ou que vous créiez un collage rapide, ImgFrame le gère instantanément sur votre appareil.",
        "labels": {
            "support": "Page d'assistance",
            "home": "Retour à Trotyl Home",
        },
    },
    "de": {
        "name": "Deutsch",
        "headline": "Verleihe deinen Fotos das perfekte Layout.",
        "blurb": "ImgFrame ist ein minimalistisches Tool, das zwei Dinge perfekt macht: Ränder zu Bildern hinzufügen und mehrere Fotos stapeln. Egal, ob du einen Beitrag für soziale Medien vorbereitest oder ein schnelles Collage erstellst, ImgFrame erledigt es sofort auf deinem Gerät.",
        "labels": {
            "support": "Support-Seite",
            "home": "Zurück zu Trotyl Home",
        },
    },
    "zh": {
        "name": "中文",
        "headline": "为你的照片打造完美布局。",
        "blurb": "ImgFrame 是一款极简工具，专注于两件事：为图片添加边框和将多张照片组合。无论你是准备社交媒体帖子还是快速拼贴，ImgFrame 都能在你的设备上即时完成。",
        "labels": {
            "support": "支持页面",
            "home": "返回 Trotyl 首页",
        },
    },
    "ja": {
        "name": "日本語",
        "headline": "写真に完璧なレイアウトを。",
        "blurb": "ImgFrame は、2つのことを完璧に行うために設計されたミニマリストツールです：画像に枠を追加し、複数の写真を組み合わせます。ソーシャルメディアの投稿を準備する場合でも、クイックコラージュを作成する場合でも、ImgFrame がデバイス上で即座に処理します。",
        "labels": {
            "support": "サポートページ",
            "home": "Trotyl ホームに戻る",
        },
    },
}

IMGFRAME_SUPPORT_COPY = {
    "en": {
        "back": "← Back to ImgFrame",
        "hero_tag": "Frame your photos perfectly, every time.",
        "hero_title": "ImgFrame Support Page.",
        "hero_body": "ImgFrame is a new app from a solo developer. If you encounter issues with borders, photo stacking, or exports, please reach out and I'll try to fix it or add support.",
        "cta_button": "Email support",
        "cta_hint": "Average reply time: under 1 business day",
        "how_title": "How to use this app",
        "how_sub": "Follow these steps to get started with ImgFrame.",
        "contact_button": "Open mail with details",
        "steps": [
            {"title": "Add borders to your photos.", "body": "Use ImgFrame's smart border feature to add white or colored borders that fit any aspect ratio without cropping your original image."},
            {"title": "Stack your photos.", "body": "Combine images vertically for long screenshots or timelines, or horizontally for comparisons and side-by-side views."},
            {"title": "Export in high resolution.", "body": "Save your photos with zero compression, maintaining full quality for your social media posts or personal use."},
            {"title": "Work offline, stay private.", "body": "ImgFrame works entirely offline. Your photos never leave your device—no uploads, no data collection, just your photos, framed perfectly."},
        ],
        "contact_title": "Contact",
        "contact_body": "Send us a note about any issues you encounter or features you'd like to see. We'll reply as quickly as we can.",
        "contact_note": "",
        "faq_title": "FAQ",
        "faq_q1": "Is my data secure?",
        "faq_sub": "Yes! ImgFrame works entirely offline. We don't collect your data, and we don't upload your photos to any server. Everything stays on your device.",
    },
    "es": {
        "back": "← Volver a ImgFrame",
        "hero_tag": "Enmarca tus fotos perfectamente, siempre.",
        "hero_title": "Página de soporte de ImgFrame.",
        "hero_body": "ImgFrame es una app nueva de un desarrollador independiente. Si encuentras problemas con bordes, apilado de fotos o exportaciones, escríbeme y trataré de arreglarlo o agregar soporte.",
        "cta_button": "Enviar correo a soporte",
        "cta_hint": "Tiempo medio de respuesta: menos de 1 día hábil",
        "how_title": "Cómo usar esta app",
        "how_sub": "Sigue estos pasos para comenzar con ImgFrame.",
        "contact_button": "Abrir correo con detalles",
        "steps": [
            {"title": "Agrega bordes a tus fotos.", "body": "Usa la función de bordes inteligentes de ImgFrame para agregar bordes blancos o de color que se ajusten a cualquier relación de aspecto sin recortar tu imagen original."},
            {"title": "Apila tus fotos.", "body": "Combina imágenes verticalmente para capturas largas o líneas de tiempo, u horizontalmente para comparaciones y vistas lado a lado."},
            {"title": "Exporta en alta resolución.", "body": "Guarda tus fotos sin compresión, manteniendo la calidad completa para tus publicaciones en redes sociales o uso personal."},
            {"title": "Trabaja offline, mantén tu privacidad.", "body": "ImgFrame funciona completamente offline. Tus fotos nunca salen de tu dispositivo: sin subidas, sin recopilación de datos, solo tus fotos, perfectamente enmarcadas."},
        ],
        "contact_title": "Contacto",
        "contact_body": "Cuéntanos sobre cualquier problema que encuentres o funciones que te gustaría ver. Responderemos lo antes posible.",
        "contact_note": "",
        "faq_title": "Preguntas frecuentes",
        "faq_q1": "¿Mis datos están seguros?",
        "faq_sub": "¡Sí! ImgFrame funciona completamente offline. No recopilamos tus datos y no subimos tus fotos a ningún servidor. Todo permanece en tu dispositivo.",
    },
    "fr": {
        "back": "← Retour à ImgFrame",
        "hero_tag": "Encadrez vos photos parfaitement, à chaque fois.",
        "hero_title": "Page d'assistance ImgFrame.",
        "hero_body": "ImgFrame est une nouvelle app développée en solo. Si vous rencontrez des problèmes avec les bordures, l'empilement de photos ou les exports, contactez-moi et j'essaierai de corriger ou d'ajouter le support.",
        "cta_button": "Contacter le support",
        "cta_hint": "Temps de réponse moyen : moins d'un jour ouvré",
        "how_title": "Comment utiliser l'app",
        "how_sub": "Suivez ces étapes pour commencer avec ImgFrame.",
        "contact_button": "Ouvrir un mail avec les détails",
        "steps": [
            {"title": "Ajoutez des bordures à vos photos.", "body": "Utilisez la fonction de bordure intelligente d'ImgFrame pour ajouter des bordures blanches ou colorées qui s'adaptent à tout format sans recadrer votre image d'origine."},
            {"title": "Empilez vos photos.", "body": "Combinez des images verticalement pour des captures longues ou des chronologies, ou horizontalement pour des comparaisons et des vues côte à côte."},
            {"title": "Exportez en haute résolution.", "body": "Enregistrez vos photos sans compression, en conservant toute la qualité pour vos publications sur les réseaux sociaux ou votre usage personnel."},
            {"title": "Travaillez hors ligne, restez privé.", "body": "ImgFrame fonctionne entièrement hors ligne. Vos photos ne quittent jamais votre appareil—pas de téléchargement, pas de collecte de données, juste vos photos, parfaitement encadrées."},
        ],
        "contact_title": "Contact",
        "contact_body": "Envoyez-nous une note sur tout problème rencontré ou fonctionnalité souhaitée. Nous répondrons dès que possible.",
        "contact_note": "",
        "faq_title": "FAQ",
        "faq_q1": "Mes données sont-elles sécurisées ?",
        "faq_sub": "Oui ! ImgFrame fonctionne entièrement hors ligne. Nous ne collectons pas vos données et nous ne téléchargeons pas vos photos sur un serveur. Tout reste sur votre appareil.",
    },
    "de": {
        "back": "← Zurück zu ImgFrame",
        "hero_tag": "Rahme deine Fotos perfekt, jedes Mal.",
        "hero_title": "ImgFrame Support-Seite.",
        "hero_body": "ImgFrame ist eine neue App von einem Solo-Entwickler. Bei Problemen mit Rändern, Foto-Stapelung oder Exporten melde dich, ich versuche es zu fixen oder zu unterstützen.",
        "cta_button": "Support per E-Mail",
        "cta_hint": "Ø Antwortzeit: unter 1 Werktag",
        "how_title": "So nutzt du die App",
        "how_sub": "Folge diesen Schritten, um mit ImgFrame zu starten.",
        "contact_button": "E-Mail mit Details öffnen",
        "steps": [
            {"title": "Füge Ränder zu deinen Fotos hinzu.", "body": "Nutze ImgFrames intelligente Randfunktion, um weiße oder farbige Ränder hinzuzufügen, die sich jedem Seitenverhältnis anpassen, ohne dein Originalbild zu beschneiden."},
            {"title": "Staple deine Fotos.", "body": "Kombiniere Bilder vertikal für lange Screenshots oder Zeitlinien, oder horizontal für Vergleiche und nebeneinander Ansichten."},
            {"title": "Exportiere in hoher Auflösung.", "body": "Speichere deine Fotos ohne Kompression und behalte die volle Qualität für deine Social-Media-Posts oder den persönlichen Gebrauch."},
            {"title": "Arbeite offline, bleib privat.", "body": "ImgFrame funktioniert vollständig offline. Deine Fotos verlassen nie dein Gerät—keine Uploads, keine Datenerfassung, nur deine Fotos, perfekt gerahmt."},
        ],
        "contact_title": "Kontakt",
        "contact_body": "Schreib uns über Probleme oder gewünschte Features. Wir antworten so schnell wie möglich.",
        "contact_note": "",
        "faq_title": "FAQ",
        "faq_q1": "Sind meine Daten sicher?",
        "faq_sub": "Ja! ImgFrame funktioniert vollständig offline. Wir erfassen keine Daten und laden keine Fotos auf einen Server hoch. Alles bleibt auf deinem Gerät.",
    },
    "zh": {
        "back": "← 返回 ImgFrame",
        "hero_tag": "每次都能完美装帧你的照片。",
        "hero_title": "ImgFrame 支持页。",
        "hero_body": "ImgFrame 是个人开发的新应用。如遇边框、照片堆叠或导出问题，欢迎联系，我会尽力修复或添加支持。",
        "cta_button": "邮件联系支持",
        "cta_hint": "平均回复时间：1 个工作日内",
        "how_title": "如何使用",
        "how_sub": "按照这些步骤开始使用 ImgFrame。",
        "contact_button": "打开邮件填写详情",
        "steps": [
            {"title": "为照片添加边框。", "body": "使用 ImgFrame 的智能边框功能添加白色或彩色边框，适配任何宽高比，无需裁剪原图。"},
            {"title": "堆叠你的照片。", "body": "垂直组合图像用于长截图或时间线，或水平组合用于对比和并排视图。"},
            {"title": "高分辨率导出。", "body": "保存照片时零压缩，为社交媒体帖子或个人使用保持完整质量。"},
            {"title": "离线工作，保护隐私。", "body": "ImgFrame 完全离线工作。你的照片永远不会离开设备——不上传，不收集数据，只有你的照片，完美装帧。"},
        ],
        "contact_title": "联系",
        "contact_body": "告诉我们你遇到的问题或希望看到的功能，我们会尽快回复。",
        "contact_note": "",
        "faq_title": "常见问题",
        "faq_q1": "我的数据安全吗？",
        "faq_sub": "是的！ImgFrame 完全离线工作。我们不收集数据，也不将照片上传到任何服务器。一切都保留在你的设备上。",
    },
    "ja": {
        "back": "← ImgFrame に戻る",
        "hero_tag": "写真を完璧にフレーム、毎回。",
        "hero_title": "ImgFrame サポートページ。",
        "hero_body": "ImgFrame は個人開発の新しいアプリです。枠、写真のスタック、またはエクスポートで問題があれば、ぜひ連絡してください、修正や対応を検討します。",
        "cta_button": "サポートにメール",
        "cta_hint": "平均返信時間：1 営業日以内",
        "how_title": "使い方",
        "how_sub": "この手順で ImgFrame を始めます。",
        "contact_button": "詳細付きメールを開く",
        "steps": [
            {"title": "写真に枠を追加。", "body": "ImgFrame のスマート枠機能を使用して、元の画像をトリミングせずに、任意のアスペクト比に適合する白またはカラーの枠を追加します。"},
            {"title": "写真をスタック。", "body": "長いスクリーンショットやタイムライン用に画像を縦に、または比較や並べて表示用に横に組み合わせます。"},
            {"title": "高解像度でエクスポート。", "body": "圧縮なしで写真を保存し、ソーシャルメディアの投稿や個人使用のために完全な品質を維持します。"},
            {"title": "オフラインで作業し、プライバシーを保護。", "body": "ImgFrame は完全にオフラインで動作します。写真はデバイスから離れることはありません—アップロードなし、データ収集なし、ただ写真を完璧にフレームします。"},
        ],
        "contact_title": "お問い合わせ",
        "contact_body": "問題や希望する機能について教えてください。できるだけ早く返信します。",
        "contact_note": "",
        "faq_title": "FAQ",
        "faq_q1": "データは安全ですか？",
        "faq_sub": "はい！ImgFrame は完全にオフラインで動作します。データを収集せず、写真をサーバーにアップロードすることもありません。すべてがデバイスに残ります。",
    },
}
