MENULY_LANGUAGE_CONTENT = {
    "en": {
        "name": "English",
        "headline": "Don't just read the menu. See the food.",
        "blurb": "Menuly is the visual menu translator that shows you real photos of the dishes you are about to order. Unlike other apps that generate fake AI food images, Menuly searches for authentic photos to show you exactly what the restaurant serves.",
        "labels": {
            "support": "Support page",
            "home": "Back to Trotyl Home",
        },
    },
    "es": {
        "name": "Español",
        "headline": "No solo leas el menú. Ve la comida.",
        "blurb": "Menuly es el traductor visual de menús que te muestra fotos reales de los platos que vas a pedir. A diferencia de otras apps que generan imágenes falsas con IA, Menuly busca fotos auténticas para mostrarte exactamente lo que sirve el restaurante.",
        "labels": {
            "support": "Página de soporte",
            "home": "Volver a Trotyl Home",
            "repo": "Repositorio en GitHub",
        },
    },
    "fr": {
        "name": "Français",
        "headline": "Ne lisez pas seulement le menu. Voyez les plats.",
        "blurb": "Menuly est le traducteur visuel de menus qui vous montre de vraies photos des plats que vous allez commander. Contrairement aux autres apps qui génèrent de fausses images IA, Menuly recherche des photos authentiques pour vous montrer exactement ce que sert le restaurant.",
        "labels": {
            "support": "Page d'assistance",
            "home": "Retour à Trotyl Home",
            "repo": "Dépôt GitHub",
        },
    },
    "de": {
        "name": "Deutsch",
        "headline": "Lies nicht nur die Karte. Sieh das Essen.",
        "blurb": "Menuly ist der visuelle Menüübersetzer, der dir echte Fotos der Gerichte zeigt, die du bestellen willst. Im Gegensatz zu anderen Apps, die falsche KI-Bilder generieren, sucht Menuly nach authentischen Fotos, um dir genau zu zeigen, was das Restaurant serviert.",
        "labels": {
            "support": "Support-Seite",
            "home": "Zurück zu Trotyl Home",
            "repo": "GitHub-Repository",
        },
    },
    "zh": {
        "name": "中文",
        "headline": "不要只读菜单。看看实物。",
        "blurb": "Menuly 是视觉菜单翻译器，向你展示即将点餐的菜品实拍照片。与其他生成虚假 AI 食物图片的应用不同，Menuly 搜索真实照片，准确展示餐厅提供的菜品。",
        "labels": {
            "support": "支持页面",
            "home": "返回 Trotyl 首页",
            "repo": "GitHub 仓库",
        },
    },
    "ja": {
        "name": "日本語",
        "headline": "メニューを読むだけじゃない。料理を見る。",
        "blurb": "Menuly は注文する料理の実物写真を表示するビジュアルメニュー翻訳アプリです。偽の AI 画像を生成する他のアプリとは違い、Menuly は本物の写真を検索し、その店が提供する料理を正確に表示します。",
        "labels": {
            "support": "サポートページ",
            "home": "Trotyl ホームに戻る",
            "repo": "GitHub リポジトリ",
        },
    },
}

MENULY_SUPPORT_COPY = {
    "en": {
        "back": "← Back to Menuly",
        "hero_tag": "See what you're ordering before you order it.",
        "hero_title": "Menuly Support Page.",
        "hero_body": "Menuly is a new app from a solo developer. If you encounter issues with menu recognition, translations, or photo matching, please reach out and I'll try to fix it or add support.",
        "cta_button": "Email support",
        "cta_hint": "Average reply time: under 1 business day",
        "how_title": "How to use this app",
        "how_sub": "Follow these steps to get started with Menuly.",
        "contact_button": "Open mail with details",
        "steps": [
            {"title": "Point your camera at the menu.", "body": "Use Menuly's camera to scan any paper menu. Our OCR technology instantly digitizes the text."},
            {"title": "View dish photos.", "body": "Menuly searches for real photos of each dish, prioritizing images from the specific restaurant you're at."},
            {"title": "Translate and understand.", "body": "Get instant translations of ingredients and descriptions in your native language alongside visual context."},
            {"title": "Order with confidence.", "body": "See exactly what you're ordering before it arrives at your table."},
        ],
        "contact_title": "Contact",
        "contact_body": "Send us a note about any issues you encounter or features you'd like to see. We'll reply as quickly as we can.",
        "contact_note": "",
        "faq_title": "FAQ",
        "faq_q1": "How does Menuly find photos?",
        "faq_sub": "Menuly uses location-based search to find authentic photos from the specific restaurant you're visiting, ensuring accuracy and relevance.",
    },
    "es": {
        "back": "← Volver a Menuly",
        "hero_tag": "Ve lo que pides antes de pedirlo.",
        "hero_title": "Página de soporte de Menuly.",
        "hero_body": "Menuly es una app nueva de un desarrollador independiente. Si encuentras problemas con el reconocimiento de menús, traducciones o coincidencia de fotos, escríbeme y trataré de arreglarlo o agregar soporte.",
        "cta_button": "Enviar correo a soporte",
        "cta_hint": "Tiempo medio de respuesta: menos de 1 día hábil",
        "how_title": "Cómo usar esta app",
        "how_sub": "Sigue estos pasos para comenzar con Menuly.",
        "contact_button": "Abrir correo con detalles",
        "steps": [
            {"title": "Apunta la cámara al menú.", "body": "Usa la cámara de Menuly para escanear cualquier menú en papel. Nuestra tecnología OCR digitaliza el texto al instante."},
            {"title": "Ve las fotos de los platos.", "body": "Menuly busca fotos reales de cada plato, priorizando imágenes del restaurante específico donde estás."},
            {"title": "Traduce y comprende.", "body": "Obtén traducciones instantáneas de ingredientes y descripciones en tu idioma junto con contexto visual."},
            {"title": "Pide con confianza.", "body": "Ve exactamente lo que pides antes de que llegue a tu mesa."},
        ],
        "contact_title": "Contacto",
        "contact_body": "Cuéntanos sobre cualquier problema que encuentres o funciones que te gustaría ver. Responderemos lo antes posible.",
        "contact_note": "Incluye el nombre del restaurante, ubicación y dispositivo que usas.",
        "faq_title": "Preguntas frecuentes",
        "faq_q1": "¿Cómo encuentra fotos Menuly?",
        "faq_sub": "Menuly usa búsqueda basada en ubicación para encontrar fotos auténticas del restaurante específico que visitas, garantizando precisión y relevancia.",
    },
    "fr": {
        "back": "← Retour à Menuly",
        "hero_tag": "Voyez ce que vous commandez avant de commander.",
        "hero_title": "Page d'assistance Menuly.",
        "hero_body": "Menuly est une nouvelle app développée en solo. Si vous rencontrez des problèmes de reconnaissance de menu, de traduction ou de correspondance de photos, contactez-moi et j'essaierai de corriger ou d'ajouter le support.",
        "cta_button": "Contacter le support",
        "cta_hint": "Temps de réponse moyen : moins d'un jour ouvré",
        "how_title": "Comment utiliser l'app",
        "how_sub": "Suivez ces étapes pour commencer avec Menuly.",
        "contact_button": "Ouvrir un mail avec les détails",
        "steps": [
            {"title": "Pointez la caméra vers le menu.", "body": "Utilisez la caméra Menuly pour scanner n'importe quel menu papier. Notre technologie OCR numérise le texte instantanément."},
            {"title": "Consultez les photos des plats.", "body": "Menuly recherche de vraies photos de chaque plat, en priorisant les images du restaurant spécifique où vous êtes."},
            {"title": "Traduisez et comprenez.", "body": "Obtenez des traductions instantanées des ingrédients et descriptions dans votre langue avec le contexte visuel."},
            {"title": "Commandez en toute confiance.", "body": "Voyez exactement ce que vous commandez avant qu'il n'arrive à votre table."},
        ],
        "contact_title": "Contact",
        "contact_body": "Envoyez-nous une note sur tout problème rencontré ou fonctionnalité souhaitée. Nous répondrons dès que possible.",
        "contact_note": "Incluez le nom du restaurant, l'emplacement et votre appareil.",
        "faq_title": "FAQ",
        "faq_q1": "Comment Menuly trouve-t-il les photos ?",
        "faq_sub": "Menuly utilise une recherche basée sur la localisation pour trouver des photos authentiques du restaurant spécifique que vous visitez, garantissant précision et pertinence.",
    },
    "de": {
        "back": "← Zurück zu Menuly",
        "hero_tag": "Sieh, was du bestellst, bevor du es bestellst.",
        "hero_title": "Menuly Support-Seite.",
        "hero_body": "Menuly ist eine neue App von einem Solo-Entwickler. Bei Problemen mit Menüerkennung, Übersetzungen oder Fotomatching melde dich, ich versuche es zu fixen oder zu unterstützen.",
        "cta_button": "Support per E-Mail",
        "cta_hint": "Ø Antwortzeit: unter 1 Werktag",
        "how_title": "So nutzt du die App",
        "how_sub": "Folge diesen Schritten, um mit Menuly zu starten.",
        "contact_button": "E-Mail mit Details öffnen",
        "steps": [
            {"title": "Richte die Kamera auf die Karte.", "body": "Nutze Menulys Kamera zum Scannen von Papierkarten. Unsere OCR-Technik digitalisiert den Text sofort."},
            {"title": "Sieh Fotos der Gerichte.", "body": "Menuly sucht echte Fotos jedes Gerichts und priorisiert Bilder vom Restaurant, wo du bist."},
            {"title": "Übersetze und verstehe.", "body": "Erhalte sofortige Übersetzungen von Zutaten und Beschreibungen in deiner Sprache mit visuellem Kontext."},
            {"title": "Bestelle selbstbewusst.", "body": "Sieh genau, was du bestellst, bevor es am Tisch ist."},
        ],
        "contact_title": "Kontakt",
        "contact_body": "Schreib uns über Probleme oder gewünschte Features. Wir antworten so schnell wie möglich.",
        "contact_note": "Bitte Restaurantname, Ort und dein Gerät angeben.",
        "faq_title": "FAQ",
        "faq_q1": "Wie findet Menuly Fotos?",
        "faq_sub": "Menuly nutzt standortbasierte Suche für authentische Fotos vom spezifischen Restaurant, das du besuchst, für Genauigkeit und Relevanz.",
    },
    "zh": {
        "back": "← 返回 Menuly",
        "hero_tag": "点餐前先看看菜品。",
        "hero_title": "Menuly 支持页。",
        "hero_body": "Menuly 是个人开发的新应用。如遇菜单识别、翻译或照片匹配问题，欢迎联系，我会尽力修复或添加支持。",
        "cta_button": "邮件联系支持",
        "cta_hint": "平均回复时间：1 个工作日内",
        "how_title": "如何使用",
        "how_sub": "按照这些步骤开始使用 Menuly。",
        "contact_button": "打开邮件填写详情",
        "steps": [
            {"title": "将相机对准菜单。", "body": "使用 Menuly 的相机扫描纸质菜单。我们的 OCR 技术可即时将文字数字化。"},
            {"title": "查看菜品照片。", "body": "Menuly 搜索每道菜品的真实照片，优先显示你所在餐厅的图片。"},
            {"title": "翻译和理解。", "body": "即时获取食材和描述的母语翻译，并结合视觉上下文。"},
            {"title": "放心点餐。", "body": "在上菜前准确看到你将点的菜品。"},
        ],
        "contact_title": "联系",
        "contact_body": "告诉我们你遇到的问题或希望看到的功能，我们会尽快回复。",
        "contact_note": "请附上餐厅名称、位置和使用设备。",
        "faq_title": "常见问题",
        "faq_q1": "Menuly 如何找到照片？",
        "faq_sub": "Menuly 使用基于位置搜索，查找你访问餐厅的真实照片，确保准确性和相关性。",
    },
    "ja": {
        "back": "← Menuly に戻る",
        "hero_tag": "注文前に料理を見る。",
        "hero_title": "Menuly サポートページ。",
        "hero_body": "Menuly は個人開発の新しいアプリです。メニュー認識、翻訳、写真マッチングで問題があれば、ぜひ連絡してください、修正や対応を検討します。",
        "cta_button": "サポートにメール",
        "cta_hint": "平均返信時間：1 営業日以内",
        "how_title": "使い方",
        "how_sub": "この手順で Menuly を始めます。",
        "contact_button": "詳細付きメールを開く",
        "steps": [
            {"title": "カメラをメニューに向ける。", "body": "Menuly のカメラで紙のメニューをスキャン。OCR 技術がテキストを即座にデジタル化します。"},
            {"title": "料理の写真を表示。", "body": "Menuly が各料理の実物写真を検索し、あなたがいる特定の店の画像を優先表示します。"},
            {"title": "翻訳して理解。", "body": "視覚的な文脈と一緒に、材料や説明を母国語で即座に翻訳します。"},
            {"title": "自信を持って注文。", "body": "テーブルに届く前に、注文する料理を正確に確認できます。"},
        ],
        "contact_title": "お問い合わせ",
        "contact_body": "問題や希望する機能について教えてください。できるだけ早く返信します。",
        "contact_note": "レストラン名、場所、使用デバイスを添えてください。",
        "faq_title": "FAQ",
        "faq_q1": "Menuly はどうやって写真を見つけますか？",
        "faq_sub": "Menuly は位置ベースの検索を使用し、訪問中の特定レストランの実物写真を見つけ、正確性と関連性を確保します。",
    },
}

