VITWO_LANGUAGE_CONTENT = {
    "en": {
        "name": "English",
        "headline": "Watch together in perfect sync.",
        "blurb": "ViTwo lets friends sync video playback across devices with one link.",
        "labels": {
            "chrome": "Chrome Web Store",
            "edge": "Microsoft Edge Add-ons",
            "support": "Support page",
            "home": "Back to Trotyl Home",
            "repo": "GitHub repo",
        },
    },
    "es": {
        "name": "Español",
        "headline": "Mira juntos en sincronía perfecta.",
        "blurb": "ViTwo sincroniza la reproducción de video entre amigos con un solo enlace.",
        "labels": {
            "chrome": "Tienda web de Chrome",
            "edge": "Complementos de Microsoft Edge",
            "support": "Página de soporte",
            "home": "Volver a Trotyl Home",
            "repo": "Repositorio en GitHub",
        },
    },
    "fr": {
        "name": "Français",
        "headline": "Regardez ensemble en parfaite synchronisation.",
        "blurb": "ViTwo synchronise la lecture vidéo entre amis avec un seul lien.",
        "labels": {
            "chrome": "Chrome Web Store",
            "edge": "Modules complémentaires Microsoft Edge",
            "support": "Page d’assistance",
            "home": "Retour à Trotyl Home",
            "repo": "Dépôt GitHub",
        },
    },
    "de": {
        "name": "Deutsch",
        "headline": "Gemeinsam perfekt synchron schauen.",
        "blurb": "ViTwo synchronisiert Videowiedergabe mit Freunden über einen Link.",
        "labels": {
            "chrome": "Chrome Web Store",
            "edge": "Microsoft Edge-Add-ons",
            "support": "Support-Seite",
            "home": "Zurück zu Trotyl Home",
            "repo": "GitHub-Repository",
        },
    },
    "zh": {
        "name": "中文",
        "headline": "一起同步观看视频。",
        "blurb": "ViTwo 通过一个链接，让朋友间的视频播放保持同步。",
        "labels": {
            "chrome": "Chrome 插件",
            "edge": "Microsoft Edge 插件",
            "support": "支持页面",
            "home": "返回 Trotyl 首页",
            "repo": "GitHub 仓库",
        },
    },
    "ja": {
        "name": "日本語",
        "headline": "みんなで動画をぴったり同期再生。",
        "blurb": "ViTwo は1つのリンクで友だちと動画を同期再生できます。",
        "labels": {
            "chrome": "Chrome ウェブストア",
            "edge": "Microsoft Edge アドオン",
            "support": "サポートページ",
            "home": "Trotyl ホームに戻る",
            "repo": "GitHub リポジトリ",
        },
    },
}

VITWO_SUPPORT_COPY = {
    "en": {
        "back": "← Back to ViTwo",
        "hero_tag": "Watch together without the hiccups.",
        "hero_title": "ViTwo Support Page.",
        "hero_body": "ViTwo is a new app from a solo developer. I can’t support every site, and some may break when their code changes—please reach out and I’ll try to fix it or add support.",
        "cta_button": "Email support",
        "cta_hint": "Average reply time: under 1 business day",
        "how_title": "How to use this app",
        "how_sub": "Follow these steps to get your room in sync.",
        "contact_button": "Open mail with details",
        "steps": [
            {"title": "Paste the video link.", "body": "Works on most sites—drop the URL into ViTwo."},
            {"title": "Press “Detect Video.”", "body": "ViTwo will read the stream info and show the duration."},
            {"title": "Check the video duration.", "body": "If it shows 0:00, switch to the page view, play the video, and press Reload until the correct duration appears."},
            {"title": "Still stuck?", "body": "Change a site or email us using the button above so we can investigate."},
        ],
        "contact_title": "Contact",
        "contact_body": "Send us a note with the site you’re on and what you expected to see. We’ll reply as quickly as we can.",
        "contact_note": "It helps to include the URL, a screenshot, and the device you’re using.",
        "faq_title": "FAQ",
        "faq_q1": "Where can I find the extension for web?",
        "faq_sub": "Choose your browser store:",
    },
    "es": {
        "back": "← Volver a ViTwo",
        "hero_tag": "Miren juntos sin interrupciones.",
        "hero_title": "Página de soporte de ViTwo.",
        "hero_body": "ViTwo es una app nueva de un desarrollador independiente. No puedo soportar todos los sitios y algunos pueden romperse cuando cambia su código. Escríbeme y trataré de arreglarlo o agregar soporte.",
        "cta_button": "Enviar correo a soporte",
        "cta_hint": "Tiempo medio de respuesta: menos de 1 día hábil",
        "how_title": "Cómo usar esta app",
        "how_sub": "Sigue estos pasos para sincronizar la sala.",
        "contact_button": "Abrir correo con detalles",
        "steps": [
            {"title": "Pega el enlace del video.", "body": "Funciona en la mayoría de los sitios—pon la URL en ViTwo."},
            {"title": "Presiona “Detectar video”.", "body": "ViTwo leerá la transmisión y mostrará la duración."},
            {"title": "Revisa la duración.", "body": "Si muestra 0:00, ve a la página, reproduce el video y presiona Recargar hasta que sea correcta."},
            {"title": "¿Aún con problemas?", "body": "Cambia de sitio o envíanos un correo con el botón para investigar."},
        ],
        "contact_title": "Contacto",
        "contact_body": "Cuéntanos en qué sitio estás y qué esperabas ver. Responderemos lo antes posible.",
        "contact_note": "Incluye la URL, una captura de pantalla y tu dispositivo.",
        "faq_title": "Preguntas frecuentes",
        "faq_q1": "¿Dónde encuentro la extensión web?",
        "faq_sub": "Elige tu tienda de navegador:",
    },
    "fr": {
        "back": "← Retour à ViTwo",
        "hero_tag": "Regardez ensemble sans accroc.",
        "hero_title": "Page d’assistance ViTwo.",
        "hero_body": "ViTwo est une nouvelle app développée en solo. Je ne peux pas supporter tous les sites et certains peuvent casser quand leur code change—contactez-moi et j’essaierai de corriger ou d’ajouter le support.",
        "cta_button": "Contacter le support",
        "cta_hint": "Temps de réponse moyen : moins d’un jour ouvré",
        "how_title": "Comment utiliser l’app",
        "how_sub": "Suivez ces étapes pour synchroniser votre salle.",
        "contact_button": "Ouvrir un mail avec les détails",
        "steps": [
            {"title": "Collez le lien vidéo.", "body": "Fonctionne sur la plupart des sites—mettez l’URL dans ViTwo."},
            {"title": "Appuyez sur « Détecter la vidéo ».", "body": "ViTwo lit le flux et affiche la durée."},
            {"title": "Vérifiez la durée.", "body": "Si c’est 0:00, passez sur la page, lisez la vidéo et rechargez jusqu’à ce que la durée soit correcte."},
            {"title": "Encore bloqué ?", "body": "Changez de site ou envoyez-nous un mail via le bouton pour qu’on enquête."},
        ],
        "contact_title": "Contact",
        "contact_body": "Envoyez-nous le site où vous êtes et ce que vous attendiez. Nous répondrons dès que possible.",
        "contact_note": "Incluez l’URL, une capture et votre appareil.",
        "faq_title": "FAQ",
        "faq_q1": "Où trouver l’extension web ?",
        "faq_sub": "Choisissez votre boutique navigateur :",
    },
    "de": {
        "back": "← Zurück zu ViTwo",
        "hero_tag": "Gemeinsam ohne Ruckeln schauen.",
        "hero_title": "ViTwo Support-Seite.",
        "hero_body": "ViTwo ist eine neue App von einem Solo-Entwickler. Ich kann nicht alle Seiten unterstützen, und manche können kaputtgehen, wenn sich ihr Code ändert—melde dich, ich versuche es zu fixen oder zu unterstützen.",
        "cta_button": "Support per E-Mail",
        "cta_hint": "Ø Antwortzeit: unter 1 Werktag",
        "how_title": "So nutzt du die App",
        "how_sub": "Folge diesen Schritten, um den Raum zu synchronisieren.",
        "contact_button": "E-Mail mit Details öffnen",
        "steps": [
            {"title": "Videolink einfügen.", "body": "Funktioniert auf den meisten Seiten—URL in ViTwo einfügen."},
            {"title": "„Video erkennen“ drücken.", "body": "ViTwo liest den Stream und zeigt die Länge an."},
            {"title": "Videolänge prüfen.", "body": "Wenn 0:00, zur Seite wechseln, Video abspielen und neu laden bis korrekt."},
            {"title": "Noch Probleme?", "body": "Wechsle die Seite oder schreib uns über den Button, damit wir nachsehen."},
        ],
        "contact_title": "Kontakt",
        "contact_body": "Schick uns die Seite und was du erwartet hast. Wir antworten so schnell wie möglich.",
        "contact_note": "Bitte URL, Screenshot und dein Gerät angeben.",
        "faq_title": "FAQ",
        "faq_q1": "Wo finde ich die Web-Erweiterung?",
        "faq_sub": "Wähle deinen Browser-Store:",
    },
    "zh": {
        "back": "← 返回 ViTwo",
        "hero_tag": "一起流畅同步观看。",
        "hero_title": "ViTwo 支持页。",
        "hero_body": "ViTwo 是个人开发的新应用，无法支持所有网站，代码更新可能会带来问题——欢迎联系，我会尽力修复或添加支持。",
        "cta_button": "邮件联系支持",
        "cta_hint": "平均回复时间：1 个工作日内",
        "how_title": "如何使用",
        "how_sub": "按照这些步骤让房间保持同步。",
        "contact_button": "打开邮件填写详情",
        "steps": [
            {"title": "粘贴视频链接。", "body": "大多数网站都能用——把 URL 放进 ViTwo。"},
            {"title": "点击“检测视频”。", "body": "ViTwo 会读取流信息并显示时长。"},
            {"title": "检查视频时长。", "body": "如果显示 0:00，切换到页面播放视频并点刷新，直到时长正确。"},
            {"title": "还遇到问题？", "body": "换个网站或用上方按钮邮件联系我们以便排查。"},
        ],
        "contact_title": "联系",
        "contact_body": "告诉我们你所在的网站和期望看到的内容，我们会尽快回复。",
        "contact_note": "请附上 URL、截图和使用的设备。",
        "faq_title": "常见问题",
        "faq_q1": "网页版插件在哪里？",
        "faq_sub": "选择你的浏览器商店：",
    },
    "ja": {
        "back": "← ViTwo に戻る",
        "hero_tag": "みんなでスムーズに同期視聴。",
        "hero_title": "ViTwo サポートページ。",
        "hero_body": "ViTwo は個人開発の新しいアプリです。すべてのサイトを保証できず、コード変更で壊れる場合もあります。ぜひ連絡してください、修正や対応を検討します。",
        "cta_button": "サポートにメール",
        "cta_hint": "平均返信時間：1 営業日以内",
        "how_title": "使い方",
        "how_sub": "この手順でルームを同期します。",
        "contact_button": "詳細付きメールを開く",
        "steps": [
            {"title": "動画リンクを貼り付け。", "body": "ほとんどのサイトで動作—URL を ViTwo に入れてください。"},
            {"title": "「動画を検出」を押す。", "body": "ViTwo がストリーム情報を読み取り、再生時間を表示します。"},
            {"title": "動画時間を確認。", "body": "0:00 の場合、ページで再生し、再読み込みを押して正しい時間が出るまで繰り返します。"},
            {"title": "まだ問題？", "body": "サイトを変えるか、上のボタンでメールして調査を依頼してください。"},
        ],
        "contact_title": "お問い合わせ",
        "contact_body": "利用中のサイトと期待した動作を教えてください。できるだけ早く返信します。",
        "contact_note": "URL・スクリーンショット・使用デバイスを添えてください。",
        "faq_title": "FAQ",
        "faq_q1": "Web 拡張機能はどこ？",
        "faq_sub": "ブラウザストアを選択：",
    },
}

APPLE_BADGE_LANG = {
    "en": ("us", "en-us"),
    "es": ("es", "es-es"),
    "fr": ("fr", "fr-fr"),
    "de": ("de", "de-de"),
    "zh": ("cn", "zh-cn"),
    "ja": ("jp", "ja-jp"),
}
